"use client";
import { Inter } from "next/font/google";
import { AuthContextProvider } from "../api/AuthContext";
import Navbar from "../components/navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} font-sans`}>
      <head>
        <link rel="stylesheet" href={inter.href} />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        <div className="video-container">
          <video src={require("../../public/login/loginbg.mp4")} autoPlay muted loop />
          <div className="video-overlay"></div>
        </div>
        <AuthContextProvider>
          <Navbar />
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
