'use client';
import React from 'react';
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '../components/navbar';
import { AuthContextProvider } from "../api/AuthContext";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

const PlanetKosmos = localFont({
  src: [
    {
      path: '../../public/fonts/PlanetKosmos.ttf',
      weight: '400'
    }
  ],
  variable: '--font-planetkosmos'
});

const Ethnocentric = localFont({
  src: [
    {
      path: '../../public/fonts/Ethnocentric.ttf',
      weight: '400'
    }
  ],
  variable: '--font-ethnocentric'
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${PlanetKosmos.variable} ${Ethnocentric.variable} font-sans`}>
      <head>
        <link rel="stylesheet" href={inter.href} />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        <AuthContextProvider>
          <Navbar />
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
